theme: jekyll-theme-minimal
title: Erica's Reloved Clothing and Accessories Shop
description: Erica-that's me-! Finally doing what I should have done years ago and opened Erica's Reloved Clothing and Accessories Shop (ER51CAS) My aim is to connect people with beautiful items of clothing and accessories that are in very good or good as new condition. I have items in all sizes but my focus is on UK sizes 12-18. Whether a piece is expensive or from the high street stores I look for pretty prints and for the classic and the quirky.
google_analytics: UA-121891375-2
